import java.time.LocalDateTime;

public class response {
    private int responseId;
    private int queryId;
    private String responseText;
    private boolean isAutoGenerated;
    private float confidenceScore;
    private LocalDateTime timestamp;

    public response(int responseId, int queryId, String responseText, float confidenceScore) {
        this.responseId = responseId;
        this.queryId = queryId;
        this.responseText = responseText;
        this.isAutoGenerated = true;
        this.confidenceScore = confidenceScore;
        this.timestamp = LocalDateTime.now();
    }

    public boolean validateResponse() {
        return confidenceScore > 0.5;
    }
}